name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    env:
      PKG_NAME: 'ToVRandomizerTools'
      SPEC_FILE: 'ToVRandomizerTools.spec'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.x

      - name: Set up Dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./

      - name: Build Executable
        run: |
          pyinstaller ${{ env.SPEC_FILE }}
        working-directory: ./

      - name: Create Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ToVRandomizerTools-windows
          path: dist/

      - name: Archive as tarball (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar cvf - ${{ env.PKG_NAME }} ${{ env.PKG_NAME }} | gzip -9 - > ${{ env.PKG_NAME }}-linux.tar.gz
        working-directory: ./dist/

      - name: Create Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ToVRandomizerTools-linux
          path: dist/${{ env.PKG_NAME }}-linux.tar.gz
          compression-level: 0

      - name: List bundle output
        run: ls -R ./dist/

  release:
    if: github.event_name == "push"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifacts@v4
        with:
          merge-multiple: true

      - name: List Downloaded Files (Debug)
        run: |
          ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ env.PKG_NAME }}-linux.tar.gz
            ${{ env.PKG_NAME }}-windows.zip